version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    env_file:
      - ./app.env
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/var/mongodb
volumes:
  mongodb: